---
title: "User Demograpic on First Session Engagement"
author: "Audreya Metz"
date: "October 27, 2018"
output: pdf_document
---

```{r setup, include=FALSE}

```


## Exploratory Data Analysis

```{r demographics}
user_profile$gender_cat[user_profile$gender=="Male"]= 0
user_profile$gender_cat[user_profile$gender=="Female"]= 1


user_profile$home_cat[user_profile$is_homeowner=="False"]= 0
user_profile$home_cat[user_profile$is_homeowner=="True"]= 1

user_profile$age_cat[user_profile$age_bucket=="(15.0, 20.0]"]= 0
user_profile$age_cat[user_profile$age_bucket=="(20.0, 25.0]"]= 1
user_profile$age_cat[user_profile$age_bucket=="(25.0, 30.0]"]= 2
user_profile$age_cat[user_profile$age_bucket=="(30.0, 35.0]"]= 3
user_profile$age_cat[user_profile$age_bucket=="(35.0, 40.0]"]= 4
user_profile$age_cat[user_profile$age_bucket=="(40.0, 45.0]"]= 5
user_profile$age_cat[user_profile$age_bucket=="(45.0, 50.0]"]= 6
user_profile$age_cat[user_profile$age_bucket=="(50.0, 55.0]"]= 7
user_profile$age_cat[user_profile$age_bucket=="(55.0, 60.0]"]= 8
user_profile$age_cat[user_profile$age_bucket=="(60.0, 65.0]"]= 9
user_profile$age_cat[user_profile$age_bucket=="(65.0, 70.0]"]= 10
user_profile$age_cat[user_profile$age_bucket=="(70.0, 75.0]"]= 11
user_profile$age_cat[user_profile$age_bucket=="(75.0, 80.0]"]= 12
user_profile$age_cat[user_profile$age_bucket=="(80.0, 85.0]"]= 13
user_profile$age_cat[user_profile$age_bucket=="(85.0, 90.0]"]= 14
user_profile$age_cat[user_profile$age_bucket=="(90.0, 95.0]"]= 15
user_profile$age_cat[user_profile$age_bucket=="(95.0, 100.0]"]= 16

user_profile$credit_cat[user_profile$credit_score_bucket=="(495.0, 500.0]"]= 0
user_profile$credit_cat[user_profile$credit_score_bucket=="(500.0, 505.0]"]= 1
user_profile$credit_cat[user_profile$credit_score_bucket=="(505.0, 510.0]"]= 2
user_profile$credit_cat[user_profile$credit_score_bucket=="(510.0, 515.0]"]= 3
user_profile$credit_cat[user_profile$credit_score_bucket=="(515.0, 520.0]"]= 4
user_profile$credit_cat[user_profile$credit_score_bucket=="(520.0, 525.0]"]= 5
user_profile$credit_cat[user_profile$credit_score_bucket=="(525.0, 530.0]"]= 6
user_profile$credit_cat[user_profile$credit_score_bucket=="(530.0, 535.0]"]= 7
user_profile$credit_cat[user_profile$credit_score_bucket=="(535.0, 540.0]"]= 8
user_profile$credit_cat[user_profile$credit_score_bucket=="(540.0, 545.0]"]= 9
user_profile$credit_cat[user_profile$credit_score_bucket=="(545.0, 550.0]"]= 10
user_profile$credit_cat[user_profile$credit_score_bucket=="(550.0, 555.0]"]= 11
user_profile$credit_cat[user_profile$credit_score_bucket=="(555.0, 560.0]"]= 12
user_profile$credit_cat[user_profile$credit_score_bucket=="(560.0, 565.0]"]= 13
user_profile$credit_cat[user_profile$credit_score_bucket=="(565.0, 570.0]"]= 14
user_profile$credit_cat[user_profile$credit_score_bucket=="(570.0, 575.0]"]= 15
user_profile$credit_cat[user_profile$credit_score_bucket=="(575.0, 580.0]"]= 16
user_profile$credit_cat[user_profile$credit_score_bucket=="(580.0, 585.0]"]= 17
user_profile$credit_cat[user_profile$credit_score_bucket=="(585.0, 590.0]"]= 18
user_profile$credit_cat[user_profile$credit_score_bucket=="(590.0, 595.0]"]= 19
user_profile$credit_cat[user_profile$credit_score_bucket=="(595.0, 600.0]"]= 20
user_profile$credit_cat[user_profile$credit_score_bucket=="(600.0, 605.0]"]= 21

user_profile$credit_cat[user_profile$credit_score_bucket=="(605.0, 610.0]"]= 22
user_profile$credit_cat[user_profile$credit_score_bucket=="(610.0, 615.0]"]= 23
user_profile$credit_cat[user_profile$credit_score_bucket=="(615.0, 620.0]"]= 24
user_profile$credit_cat[user_profile$credit_score_bucket=="(620.0, 625.0]"]= 25
user_profile$credit_cat[user_profile$credit_score_bucket=="(625.0, 630.0]"]= 26
user_profile$credit_cat[user_profile$credit_score_bucket=="(630.0, 635.0]"]= 27
user_profile$credit_cat[user_profile$credit_score_bucket=="(635.0, 640.0]"]= 28
user_profile$credit_cat[user_profile$credit_score_bucket=="(640.0, 645.0]"]= 29
user_profile$credit_cat[user_profile$credit_score_bucket=="(645.0, 650.0]"]= 30
user_profile$credit_cat[user_profile$credit_score_bucket=="(650.0, 655.0]"]= 31
user_profile$credit_cat[user_profile$credit_score_bucket=="(655.0, 660.0]"]= 32
user_profile$credit_cat[user_profile$credit_score_bucket=="(660.0, 665.0]"]= 33
user_profile$credit_cat[user_profile$credit_score_bucket=="(665.0, 670.0]"]= 34
user_profile$credit_cat[user_profile$credit_score_bucket=="(670.0, 675.0]"]= 35
user_profile$credit_cat[user_profile$credit_score_bucket=="(675.0, 680.0]"]= 36
user_profile$credit_cat[user_profile$credit_score_bucket=="(680.0, 685.0]"]= 37
user_profile$credit_cat[user_profile$credit_score_bucket=="(685.0, 690.0]"]= 38
user_profile$credit_cat[user_profile$credit_score_bucket=="(690.0, 695.0]"]= 39
user_profile$credit_cat[user_profile$credit_score_bucket=="(695.0, 600.0]"]= 40
user_profile$credit_cat[user_profile$credit_score_bucket=="(700.0, 705.0]"]= 41

user_profile$credit_cat[user_profile$credit_score_bucket=="(705.0, 710.0]"]= 42
user_profile$credit_cat[user_profile$credit_score_bucket=="(710.0, 715.0]"]= 43
user_profile$credit_cat[user_profile$credit_score_bucket=="(715.0, 720.0]"]= 44
user_profile$credit_cat[user_profile$credit_score_bucket=="(720.0, 725.0]"]= 45
user_profile$credit_cat[user_profile$credit_score_bucket=="(725.0, 730.0]"]= 46
user_profile$credit_cat[user_profile$credit_score_bucket=="(730.0, 735.0]"]= 47
user_profile$credit_cat[user_profile$credit_score_bucket=="(735.0, 740.0]"]= 48
user_profile$credit_cat[user_profile$credit_score_bucket=="(740.0, 745.0]"]= 49
user_profile$credit_cat[user_profile$credit_score_bucket=="(745.0, 750.0]"]= 50
user_profile$credit_cat[user_profile$credit_score_bucket=="(750.0, 755.0]"]= 51
user_profile$credit_cat[user_profile$credit_score_bucket=="(755.0, 760.0]"]= 52
user_profile$credit_cat[user_profile$credit_score_bucket=="(760.0, 765.0]"]= 53
user_profile$credit_cat[user_profile$credit_score_bucket=="(765.0, 770.0]"]= 54
user_profile$credit_cat[user_profile$credit_score_bucket=="(770.0, 775.0]"]= 55
user_profile$credit_cat[user_profile$credit_score_bucket=="(775.0, 780.0]"]= 56
user_profile$credit_cat[user_profile$credit_score_bucket=="(780.0, 785.0]"]= 57
user_profile$credit_cat[user_profile$credit_score_bucket=="(785.0, 790.0]"]= 58
user_profile$credit_cat[user_profile$credit_score_bucket=="(790.0, 795.0]"]= 59
user_profile$credit_cat[user_profile$credit_score_bucket=="(795.0, 800.0]"]= 60


firstreg <- lm(credit_cat~ home_cat + count_tradelines_open_collection_accounts + max_cc_limit + tradelines_avg_days_since_opened, user_profile)

summary(firstreg)

plot(predict(firstreg),residuals(firstreg))
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
